sudo: required

services:
  - docker

language: java

#env:
#  global:
#    - GRADLE_CACHES="/home/travis/.gradle/"
#    - DOCKER_GRADLE_CACHES="/root/.gradle/"
#
#before_install:
#  # Load cached docker images
#  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
#
#before_cache:
#  # Save tagged docker images
#  - >
#    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
#    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
#  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
#  - rm -rf $HOME/.gradle/caches/*/scripts/
#  - rm -rf $HOME/.gradle/caches/*/file-changes/
#  - rm -rf $HOME/.gradle/caches/*/fileHashes/
#cache:
#  directories:
#    - $HOME/docker
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/
